In [60]:
import pandas as pd
from pydataset import data
df = data("mtcars")
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

# 1. Group by one Column

In [3]:
df.groupby("cyl")["mpg"].mean() # Avg MPG by Cylinder

cyl
4    26.663636
6    19.742857
8    15.100000
Name: mpg, dtype: float64

# 2. Count Cars in each cylinder

In [4]:
df.groupby("cyl").size()

cyl
4    11
6     7
8    14
dtype: int64

In [5]:
df.groupby("cyl").count()

     mpg  disp  hp  drat  wt  qsec  vs  am  gear  carb
cyl
4     11    11  11    11  11    11  11  11    11    11
6      7     7   7     7   7     7   7   7     7     7
8     14    14  14    14  14    14  14  14    14    14

In [6]:
df.groupby("cyl").value_counts()

cyl  mpg   disp   hp   drat  wt     qsec   vs  am  gear  carb
4    21.4  121.0  109  4.11  2.780  18.60  1   1   4     2       1
     21.5  120.1  97   3.70  2.465  20.01  1   0   3     1       1
     22.8  108.0  93   3.85  2.320  18.61  1   1   4     1       1
           140.8  95   3.92  3.150  22.90  1   0   4     2       1
     24.4  146.7  62   3.69  3.190  20.00  1   0   4     2       1
     26.0  120.3  91   4.43  2.140  16.70  0   1   5     2       1
     27.3  79.0   66   4.08  1.935  18.90  1   1   4     1       1
     30.4  75.7   52   4.93  1.615  18.52  1   1   4     2       1
           95.1   113  3.77  1.513  16.90  1   1   5     2       1
     32.4  78.7   66   4.08  2.200  19.47  1   1   4     1       1
     33.9  71.1   65   4.22  1.835  19.90  1   1   4     1       1
6    17.8  167.6  123  3.92  3.440  18.90  1   0   4     4       1
     18.1  225.0  105  2.76  3.460  20.22  1   0   3     1       1
     19.2  167.6  123  3.92  3.440  18.30  1   0   4     4       1
     19.7  145.0  175  3.62  2.770  15.50  0   1   5     6       1
     21.0  160.0  110  3.90  2.620  16.46  0   1   4     4       1
                             2.875  17.02  0   1   4     4       1
     21.4  258.0  110  3.08  3.215  19.44  1   0   3     1       1
8    10.4  460.0  215  3.00  5.424  17.82  0   0   3     4       1
           472.0  205  2.93  5.250  17.98  0   0   3     4       1
     13.3  350.0  245  3.73  3.840  15.41  0   0   3     4       1
     14.3  360.0  245  3.21  3.570  15.84  0   0   3     4       1
     14.7  440.0  230  3.23  5.345  17.42  0   0   3     4       1
     15.0  301.0  335  3.54  3.570  14.60  0   1   5     8       1
     15.2  275.8  180  3.07  3.780  18.00  0   0   3     3       1
           304.0  150  3.15  3.435  17.30  0   0   3     2       1
     15.5  318.0  150  2.76  3.520  16.87  0   0   3     2       1
     15.8  351.0  264  4.22  3.170  14.50  0   1   5     4       1
     16.4  275.8  180  3.07  4.070  17.40  0   0   3     3       1
     17.3  275.8  180  3.07  3.730  17.60  0   0   3     3       1
     18.7  360.0  175  3.15  3.440  17.02  0   0   3     2       1
     19.2  400.0  175  3.08  3.845  17.05  0   0   3     2       1
Name: count, dtype: int64

# 3. Total Horsepower by Cylinder

In [7]:
df.groupby("cyl")["hp"].sum()

cyl
4     909
6     856
8    2929
Name: hp, dtype: int64

# 4. Minimum MPG by Cylinder

In [8]:
df.groupby("cyl")["mpg"].min()

cyl
4    21.4
6    17.8
8    10.4
Name: mpg, dtype: float64

# 5. Maximum MPG by Cylinder

In [9]:
df.groupby("cyl")["mpg"].max()

cyl
4    33.9
6    21.4
8    19.2
Name: mpg, dtype: float64

# 6. Multiple Aggregations

In [10]:
df.groupby("cyl")["mpg"].agg(["mean","max","min","count"])

          mean   max   min  count
cyl
4    26.663636  33.9  21.4     11
6    19.742857  21.4  17.8      7
8    15.100000  19.2  10.4     14

# 7. Group by Multiple Columns

In [11]:
df.groupby(["cyl","am"])["mpg"].mean()

cyl  am
4    0     22.900000
     1     28.075000
6    0     19.125000
     1     20.566667
8    0     15.050000
     1     15.400000
Name: mpg, dtype: float64

# 8. Multiple Columns Aggregation

In [12]:
df.groupby("gear")[["mpg","hp"]].mean()

            mpg          hp
gear
3     16.106667  176.133333
4     24.533333   89.500000
5     21.380000  195.600000

# 9. Mean of All Numeric Columns

In [13]:
df.groupby("gear").mean(numeric_only=True)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,carb
gear,,,,,,,,,,
3,16.106667,7.466667,326.300000,176.133333,3.132667,3.892600,17.692,0.200000,0.000000,2.666667
4,24.533333,4.666667,123.016667,89.500000,4.043333,2.616667,18.965,0.833333,0.666667,2.333333
5,21.380000,6.000000,202.480000,195.600000,3.916000,2.632600,15.640,0.200000,1.000000,4.400000

In [14]:
df.groupby("gear")["mpg"].mean(numeric_only=True)

gear
3    16.106667
4    24.533333
5    21.380000
Name: mpg, dtype: float64

# 10. Aggregate Different Functions

In [15]:
df.groupby("mpg").agg({"gear":"mean","hp":"min","cyl":"max"})

      gear   hp  cyl
mpg
10.4   3.0  205    8
13.3   3.0  245    8
14.3   3.0  245    8
14.7   3.0  230    8
15.0   5.0  335    8
15.2   3.0  150    8
15.5   3.0  150    8
15.8   5.0  264    8
16.4   3.0  180    8
17.3   3.0  180    8
17.8   4.0  123    6
18.1   3.0  105    6
18.7   3.0  175    8
19.2   3.5  123    8
19.7   5.0  175    6
21.0   4.0  110    6
21.4   3.5  109    6
21.5   3.0   97    4
22.8   4.0   93    4
24.4   4.0   62    4
26.0   5.0   91    4
27.3   4.0   66    4
30.4   4.5   52    4
32.4   4.0   66    4
33.9   4.0   65    4

# 11. Rename Aggregate Columns

In [16]:
df.groupby("gear").agg(Average_MPG=("mpg","mean"),Total_HP=("hp","sum"),Max_Weight=("wt","max"))

      Average_MPG  Total_HP  Max_Weight
gear
3       16.106667      2642       5.424
4       24.533333      1074       3.440
5       21.380000       978       3.570

# 12. Find Highest Hp Car in Each Cylinder

In [17]:
df.groupby("cyl")["hp"].max()

cyl
4    113
6    175
8    335
Name: hp, dtype: int64

# 13. Find Lowest Wt Car in Each Cylinder¶

In [18]:
df.groupby("cyl")["wt"].min()

cyl
4    1.513
6    2.620
8    3.170
Name: wt, dtype: float64

# 14. Count Manual Vs Automatic

In [19]:
df.groupby("am").size()

am
0    19
1    13
dtype: int64

# 15. Average Wt by Gear

In [20]:
df.groupby("gear")["wt"].mean()

gear
3    3.892600
4    2.616667
5    2.632600
Name: wt, dtype: float64

# 16. Average Quarter Mile time

In [21]:
df.groupby("gear")["qsec"].mean()

gear
3    17.692
4    18.965
5    15.640
Name: qsec, dtype: float64

# 17. Sort Group Results

In [22]:
df.groupby("cyl")["mpg"].mean().sort_values(ascending=False)

cyl
4    26.663636
6    19.742857
8    15.100000
Name: mpg, dtype: float64

# 18. Multiple Statistics

In [25]:
df.groupby("gear")["hp"].describe()

      count        mean         std   min     25%    50%    75%    max
gear
3      15.0  176.133333   47.689272  97.0  150.00  180.0  210.0  245.0
4      12.0   89.500000   25.893137  52.0   65.75   94.0  110.0  123.0
5       5.0  195.600000  102.833847  91.0  113.00  175.0  264.0  335.0

In [26]:
df.groupby("cyl")["hp"].describe()

     count        mean        std    min     25%    50%     75%    max
cyl
4     11.0   82.636364  20.934530   52.0   65.50   91.0   96.00  113.0
6      7.0  122.285714  24.260491  105.0  110.00  110.0  123.00  175.0
8     14.0  209.214286  50.976886  150.0  176.25  192.5  241.25  335.0

# 19. Custom Aggregation

In [27]:
df.groupby("cyl")["mpg"].agg(lambda x : x.max()-x.min()) # Range= Max-min

cyl
4    12.5
6     3.6
8     8.8
Name: mpg, dtype: float64

# 20. Group BY AND Reset Index

In [28]:
df.groupby("gear")["mpg"].mean().reset_index()

   gear        mpg
0     3  16.106667
1     4  24.533333
2     5  21.380000

# 21. Named Aggregation

In [29]:
df.groupby("cyl").agg(Avg_Mpg=("mpg","mean"), Avg_Hp=("hp","mean"),Count=("wt","count"))

       Avg_Mpg      Avg_Hp  Count
cyl
4    26.663636   82.636364     11
6    19.742857  122.285714      7
8    15.100000  209.214286     14

# 22. Filter Groups

In [30]:
df.groupby("cyl").filter(lambda x :len(x)>10)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

# 22.Transform

In [32]:
df["Avg_Mpg"]= df.groupby("cyl")["mpg"].transform("mean")
df

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Avg_Mpg
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,19.742857
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,19.742857
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,26.663636
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,19.742857
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,15.100000
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,19.742857
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,15.100000
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,26.663636
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,26.663636
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,19.742857
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,19.742857
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,15.100000
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,15.100000
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,15.100000
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,15.100000
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,15.100000
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,15.100000
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,26.663636
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,26.663636
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,26.663636
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,26.663636
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,15.100000
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,15.100000
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,15.100000
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,15.100000
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,26.663636
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,26.663636
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,26.663636
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,15.100000
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,19.742857
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,15.100000
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,26.663636

# 24. Rank Within Each Cylinder

In [35]:
df["HP_Rank"]= df.groupby("cyl")["hp"].rank(ascending=False)
df

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Avg_Mpg,HP_Rank
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,19.742857,5.0
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,19.742857,5.0
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,26.663636,5.0
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,19.742857,5.0
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,15.100000,11.5
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,19.742857,7.0
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,15.100000,3.5
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,26.663636,10.0
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,26.663636,4.0
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,19.742857,2.5
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,19.742857,2.5
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,15.100000,9.0
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,15.100000,9.0
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,15.100000,9.0
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,15.100000,7.0
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,15.100000,6.0
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,15.100000,5.0
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,26.663636,7.5
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,26.663636,11.0
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,26.663636,9.0
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,26.663636,3.0
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,15.100000,13.5
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,15.100000,13.5
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,15.100000,3.5
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,15.100000,11.5
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,26.663636,7.5
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,26.663636,6.0
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,26.663636,1.0
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,15.100000,2.0
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,19.742857,1.0
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,15.100000,1.0
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,26.663636,2.0

# 25. Highest Horsepower Car per Cylinder

In [38]:
df.loc[df.groupby("cyl")["hp"].idxmax()]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Avg_Mpg,HP_Rank
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.9,1,1,5,2,26.663636,1.0
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.5,0,1,5,6,19.742857,1.0
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.6,0,1,5,8,15.100000,1.0

# 26. Lowest MPG Car per Cylinder

In [39]:
df.loc[df.groupby("cyl")["mpg"].idxmin()]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Avg_Mpg,HP_Rank
Volvo 142E,21.4,4,121.0,109,4.11,2.78,18.60,1,1,4,2,26.663636,2.0
Merc 280C,17.8,6,167.6,123,3.92,3.44,18.90,1,0,4,4,19.742857,2.5
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.25,17.98,0,0,3,4,15.100000,7.0

# 27. Apply Custom Function

In [42]:
def mpg_range(group) : return group.max()-group.min()
df.groupby("cyl")["mpg"].apply(mpg_range)

cyl
4    12.5
6     3.6
8     8.8
Name: mpg, dtype: float64

In [43]:
def mpg_range(x) : return x.max()-x.min()
df.groupby("cyl")["mpg"].apply(mpg_range)

cyl
4    12.5
6     3.6
8     8.8
Name: mpg, dtype: float64

# 28. Percentage of Total Horsepower

In [47]:
df["Hp Percentage"]= (df["hp"] / df["hp"].sum())*100
df

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Avg_Mpg,HP_Rank,Hp Percentage
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,19.742857,5.0,2.343417
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,19.742857,5.0,2.343417
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,26.663636,5.0,1.981253
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,19.742857,5.0,2.343417
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,15.100000,11.5,3.728164
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,19.742857,7.0,2.236898
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,15.100000,3.5,5.219429
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,26.663636,10.0,1.320835
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,26.663636,4.0,2.023860
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,19.742857,2.5,2.620366
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,19.742857,2.5,2.620366
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,15.100000,9.0,3.834683
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,15.100000,9.0,3.834683
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,15.100000,9.0,3.834683
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,15.100000,7.0,4.367277
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,15.100000,6.0,4.580315
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,15.100000,5.0,4.899872
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,26.663636,7.5,1.406050
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,26.663636,11.0,1.107797
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,26.663636,9.0,1.384746
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,26.663636,3.0,2.066468
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,15.100000,13.5,3.195569
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,15.100000,13.5,3.195569
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,15.100000,3.5,5.219429
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,15.100000,11.5,3.728164
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,26.663636,7.5,1.406050
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,26.663636,6.0,1.938645
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,26.663636,1.0,2.407329
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,15.100000,2.0,5.624201
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,19.742857,1.0,3.728164
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,15.100000,1.0,7.136770
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,26.663636,2.0,2.322113

# 29.Percentage Within Each Cylinder

In [51]:
df["Cylinder_Hp%"]=(df["hp"] / df.groupby("cyl")["hp"].transform("sum"))*100
df

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Avg_Mpg,HP_Rank,Hp Percentage,Cylinder_Hp%
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,19.742857,5.0,2.343417,12.850467
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,19.742857,5.0,2.343417,12.850467
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,26.663636,5.0,1.981253,10.231023
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,19.742857,5.0,2.343417,12.850467
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,15.100000,11.5,3.728164,5.974735
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,19.742857,7.0,2.236898,12.266355
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,15.100000,3.5,5.219429,8.364630
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,26.663636,10.0,1.320835,6.820682
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,26.663636,4.0,2.023860,10.451045
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,19.742857,2.5,2.620366,14.369159
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,19.742857,2.5,2.620366,14.369159
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,15.100000,9.0,3.834683,6.145442
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,15.100000,9.0,3.834683,6.145442
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,15.100000,9.0,3.834683,6.145442
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,15.100000,7.0,4.367277,6.998976
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,15.100000,6.0,4.580315,7.340389
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,15.100000,5.0,4.899872,7.852509
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,26.663636,7.5,1.406050,7.260726
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,26.663636,11.0,1.107797,5.720572
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,26.663636,9.0,1.384746,7.150715
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,26.663636,3.0,2.066468,10.671067
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,15.100000,13.5,3.195569,5.121202
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,15.100000,13.5,3.195569,5.121202
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,15.100000,3.5,5.219429,8.364630
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,15.100000,11.5,3.728164,5.974735
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,26.663636,7.5,1.406050,7.260726
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,26.663636,6.0,1.938645,10.011001
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,26.663636,1.0,2.407329,12.431243
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,15.100000,2.0,5.624201,9.013315
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,19.742857,1.0,3.728164,20.443925
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,15.100000,1.0,7.136770,11.437351
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,26.663636,2.0,2.322113,11.991199

# 30. Groupby + Value Counts

In [53]:
df.groupby("cyl")["am"].value_counts()

cyl  am
4    1      8
     0      3
6    0      4
     1      3
8    0     12
     1      2
Name: count, dtype: int64

# 31. Groupby + First Row

In [61]:
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [62]:
df.groupby("gear").first()

       mpg  cyl   disp   hp  drat     wt   qsec  vs  am  carb
gear
3     21.4    6  258.0  110  3.08  3.215  19.44   1   0     1
4     21.0    6  160.0  110  3.90  2.620  16.46   0   1     4
5     26.0    4  120.3   91  4.43  2.140  16.70   0   1     2

# 32. Groupby + Last Row

In [63]:
df.groupby("gear").first()

       mpg  cyl   disp   hp  drat     wt   qsec  vs  am  carb
gear
3     21.4    6  258.0  110  3.08  3.215  19.44   1   0     1
4     21.0    6  160.0  110  3.90  2.620  16.46   0   1     4
5     26.0    4  120.3   91  4.43  2.140  16.70   0   1     2

# 33. Groupby + Head()

In [69]:
df.groupby("cyl").head(2)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2

# 34. Groupby + Tail()

In [70]:
df.groupby("cyl").tail(2)

                 mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  carb
Merc 280C       17.8    6  167.6  123  3.92  3.440  18.9   1   0     4     4
Lotus Europa    30.4    4   95.1  113  3.77  1.513  16.9   1   1     5     2
Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5     4
Ferrari Dino    19.7    6  145.0  175  3.62  2.770  15.5   0   1     5     6
Maserati Bora   15.0    8  301.0  335  3.54  3.570  14.6   0   1     5     8
Volvo 142E      21.4    4  121.0  109  4.11  2.780  18.6   1   1     4     2

# 35. Groupby + nth()¶

In [71]:
df.groupby("cyl").nth(2) # Second Car from each cylinder group

                 mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
Merc 230        22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
Merc 450SE      16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3

# 36. Groupby + cumcount()

In [73]:
df["Row_No"]=df.groupby("cyl")["hp"].cumcount() # Assign row numbers within each cylinder group
df

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Row_No
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,0
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,1
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,0
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,2
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,0
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,3
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,1
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,1
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,2
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,4
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,5
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,2
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,3
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,4
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,5
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,6
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,7
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,3
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,4
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,5
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,6
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,8
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,9
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,10
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,11
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,7
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,8
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,9
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,12
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,6
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,13
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,10

# 37. Groupby + Cumsum()

In [74]:
df["Running_HP"]= df.groupby("cyl")["hp"].cumsum() # Running total horsepower within each cylinder
df

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Row_No,Running_HP
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,0,110
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,1,220
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,0,93
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,2,330
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,0,175
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,3,435
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,1,420
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,1,155
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,2,250
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,4,558
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,5,681
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,2,600
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,3,780
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,4,960
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,5,1165
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,6,1380
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,7,1610
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,3,316
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,4,368
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,5,433
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,6,530
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,8,1760
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,9,1910
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,10,2155
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,11,2330
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,7,596
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,8,687
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,9,800
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,12,2594
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,6,856
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,13,2929
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,10,909

# 38. Groupby + Shift()

In [75]:
df["Previous_Hp"]= df.groupby("cyl")["hp"].shift()
df

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Row_No,Running_HP,Previous_Hp
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,0,110,NaN
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,1,220,110.0
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,0,93,NaN
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,2,330,110.0
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,0,175,NaN
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,3,435,110.0
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,1,420,175.0
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,1,155,93.0
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,2,250,62.0
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,4,558,105.0
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,5,681,123.0
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,2,600,245.0
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,3,780,180.0
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,4,960,180.0
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,5,1165,180.0
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,6,1380,205.0
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,7,1610,215.0
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,3,316,95.0
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,4,368,66.0
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,5,433,52.0
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,6,530,65.0
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,8,1760,230.0
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,9,1910,150.0
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,10,2155,150.0
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,11,2330,245.0
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,7,596,97.0
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,8,687,66.0
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,9,800,91.0
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,12,2594,175.0
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,6,856,123.0
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,13,2929,264.0
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,10,909,113.0

# 39. Groupby + Diff()

In [76]:
df["HP_Diff"]=df.groupby("cyl")["hp"].diff() # Difference in horsepower from previous row
df

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Row_No,Running_HP,Previous_Hp,HP_Diff
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,0,110,NaN,NaN
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,1,220,110.0,0.0
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,0,93,NaN,NaN
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,2,330,110.0,0.0
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,0,175,NaN,NaN
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,3,435,110.0,-5.0
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,1,420,175.0,70.0
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,1,155,93.0,-31.0
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,2,250,62.0,33.0
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,4,558,105.0,18.0
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,5,681,123.0,0.0
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,2,600,245.0,-65.0
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,3,780,180.0,0.0
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,4,960,180.0,0.0
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,5,1165,180.0,25.0
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,6,1380,205.0,10.0
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,7,1610,215.0,15.0
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,3,316,95.0,-29.0
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,4,368,66.0,-14.0
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,5,433,52.0,13.0
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,6,530,65.0,32.0
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,8,1760,230.0,-80.0
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,9,1910,150.0,0.0
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,10,2155,150.0,95.0
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,11,2330,245.0,-70.0
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,7,596,97.0,-31.0
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,8,687,66.0,25.0
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,9,800,91.0,22.0
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,12,2594,175.0,89.0
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,6,856,123.0,52.0
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,13,2929,264.0,71.0
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,10,909,113.0,-4.0

# 40. Groupby + Rolling()

In [78]:
df["Rolling_MPG"]= (df.groupby("cyl")["mpg"].rolling(2).mean().reset_index(level=0,drop=True))
df

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Row_No,Running_HP,Previous_Hp,HP_Diff,Rolling_MPG
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,0,110,NaN,NaN,NaN
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,1,220,110.0,0.0,21.00
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,0,93,NaN,NaN,NaN
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,2,330,110.0,0.0,21.20
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,0,175,NaN,NaN,NaN
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,3,435,110.0,-5.0,19.75
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,1,420,175.0,70.0,16.50
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,1,155,93.0,-31.0,23.60
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,2,250,62.0,33.0,23.60
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,4,558,105.0,18.0,18.65
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,5,681,123.0,0.0,18.50
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,2,600,245.0,-65.0,15.35
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,3,780,180.0,0.0,16.85
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,4,960,180.0,0.0,16.25
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,5,1165,180.0,25.0,12.80
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,6,1380,205.0,10.0,10.40
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,7,1610,215.0,15.0,12.55
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,3,316,95.0,-29.0,27.60
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,4,368,66.0,-14.0,31.40
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,5,433,52.0,13.0,32.15
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,6,530,65.0,32.0,27.70
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,8,1760,230.0,-80.0,15.10
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,9,1910,150.0,0.0,15.35
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,10,2155,150.0,95.0,14.25
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,11,2330,245.0,-70.0,16.25
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,7,596,97.0,-31.0,24.40
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,8,687,66.0,25.0,26.65
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,9,800,91.0,22.0,28.20
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,12,2594,175.0,89.0,17.50
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,6,856,123.0,52.0,18.75
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,13,2929,264.0,71.0,15.40
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,10,909,113.0,-4.0,25.90

In [79]:
df["Rolling_MPG"]= df.groupby("cyl")["mpg"].rolling(2).mean().reset_index(level=0,drop=True)
df

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Row_No,Running_HP,Previous_Hp,HP_Diff,Rolling_MPG
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,0,110,NaN,NaN,NaN
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,1,220,110.0,0.0,21.00
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,0,93,NaN,NaN,NaN
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,2,330,110.0,0.0,21.20
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,0,175,NaN,NaN,NaN
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,3,435,110.0,-5.0,19.75
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,1,420,175.0,70.0,16.50
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,1,155,93.0,-31.0,23.60
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,2,250,62.0,33.0,23.60
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,4,558,105.0,18.0,18.65
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,5,681,123.0,0.0,18.50
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,2,600,245.0,-65.0,15.35
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,3,780,180.0,0.0,16.85
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,4,960,180.0,0.0,16.25
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,5,1165,180.0,25.0,12.80
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,6,1380,205.0,10.0,10.40
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,7,1610,215.0,15.0,12.55
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,3,316,95.0,-29.0,27.60
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,4,368,66.0,-14.0,31.40
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,5,433,52.0,13.0,32.15
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,6,530,65.0,32.0,27.70
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,8,1760,230.0,-80.0,15.10
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,9,1910,150.0,0.0,15.35
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,10,2155,150.0,95.0,14.25
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,11,2330,245.0,-70.0,16.25
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,7,596,97.0,-31.0,24.40
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,8,687,66.0,25.0,26.65
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,9,800,91.0,22.0,28.20
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,12,2594,175.0,89.0,17.50
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,6,856,123.0,52.0,18.75
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,13,2929,264.0,71.0,15.40
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,10,909,113.0,-4.0,25.90