In [120]:
import pandas as pd
from pydataset import data
df = data ('mtcars')

# 1. HEAD()

In [73]:
df.head() # display the first few rows

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [74]:
df.head(10)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4

# 2. Tail()

In [75]:
df.tail() # displays the last 5 rows

                 mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  carb
Lotus Europa    30.4    4   95.1  113  3.77  1.513  16.9   1   1     5     2
Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5     4
Ferrari Dino    19.7    6  145.0  175  3.62  2.770  15.5   0   1     5     6
Maserati Bora   15.0    8  301.0  335  3.54  3.570  14.6   0   1     5     8
Volvo 142E      21.4    4  121.0  109  4.11  2.780  18.6   1   1     4     2

In [76]:
df.tail(10)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

# 3. Sample()

In [77]:
df.sample() # return random rows, useful for inspecting large datasets

             mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  carb
Duster 360  14.3    8  360.0  245  3.21  3.57  15.84   0   0     3     4

In [78]:
df.sample(10)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1

# 4. Info()

In [79]:
df.info() # provides a summary of the dataframe.Number of rows,columns,data types,missing values,memory usages.

<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, Mazda RX4 to Volvo 142E
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   mpg     32 non-null     float64
 1   cyl     32 non-null     int64
 2   disp    32 non-null     float64
 3   hp      32 non-null     int64
 4   drat    32 non-null     float64
 5   wt      32 non-null     float64
 6   qsec    32 non-null     float64
 7   vs      32 non-null     int64
 8   am      32 non-null     int64
 9   gear    32 non-null     int64
 10  carb    32 non-null     int64
dtypes: float64(5), int64(6)
memory usage: 3.0+ KB

# 5. Describe()

In [80]:
df.describe() # Generates descriptive satistics for numeric columns. includes- count,mean,min,max,standart deviation,quartiles

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

# 6.Value_Counts()

In [81]:
df["am"].value_counts() # Counts unique values in a columns

am
0    19
1    13
Name: count, dtype: int64

# 7. Unique()

In [82]:
df["am"].unique() # Returns unique values

array([1, 0])

# 8. Nunique()

In [83]:
df["am"].nunique() # Counts unique values

2

# 9. Sort_Values()

In [84]:
df.sort_values("am", ascending=False) # Sorts rows by column values

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4

In [85]:
df.sort_values("am", ascending=True)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

# 10. Sort_Index()

In [86]:
df.sort_index()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [87]:
# df.reset_index(inplace = True)

# 11. Groupby()

In [88]:
df.groupby("am")["hp"].mean() # Group data/rows before aggregation

am
0    160.263158
1    126.846154
Name: hp, dtype: float64

# 12. Agg()

In [89]:
df.groupby('am').agg(avg_mpg=('mpg','mean'),max_hp=('hp','max'),avg_weight=('wt','mean'))

      avg_mpg  max_hp  avg_weight
am
0   17.147368     245    3.768895
1   24.392308     335    2.411000

In [90]:
df.groupby('am').agg({"mpg":["sum","mean"],"hp":"max"})

      mpg              hp
      sum       mean  max
am
0   325.8  17.147368  245
1   317.1  24.392308  335

In [91]:
df.groupby('mpg').agg('sum','max')

      cyl   disp   hp  drat      wt   qsec  vs  am  gear  carb
mpg
10.4   16  932.0  420  5.93  10.674  35.80   0   0     6     8
13.3    8  350.0  245  3.73   3.840  15.41   0   0     3     4
14.3    8  360.0  245  3.21   3.570  15.84   0   0     3     4
14.7    8  440.0  230  3.23   5.345  17.42   0   0     3     4
15.0    8  301.0  335  3.54   3.570  14.60   0   1     5     8
15.2   16  579.8  330  6.22   7.215  35.30   0   0     6     5
15.5    8  318.0  150  2.76   3.520  16.87   0   0     3     2
15.8    8  351.0  264  4.22   3.170  14.50   0   1     5     4
16.4    8  275.8  180  3.07   4.070  17.40   0   0     3     3
17.3    8  275.8  180  3.07   3.730  17.60   0   0     3     3
17.8    6  167.6  123  3.92   3.440  18.90   1   0     4     4
18.1    6  225.0  105  2.76   3.460  20.22   1   0     3     1
18.7    8  360.0  175  3.15   3.440  17.02   0   0     3     2
19.2   14  567.6  298  7.00   7.285  35.35   1   0     7     6
19.7    6  145.0  175  3.62   2.770  15.50   0   1     5     6
21.0   12  320.0  220  7.80   5.495  33.48   0   2     8     8
21.4   10  379.0  219  7.19   5.995  38.04   2   1     7     3
21.5    4  120.1   97  3.70   2.465  20.01   1   0     3     1
22.8    8  248.8  188  7.77   5.470  41.51   2   1     8     3
24.4    4  146.7   62  3.69   3.190  20.00   1   0     4     2
26.0    4  120.3   91  4.43   2.140  16.70   0   1     5     2
27.3    4   79.0   66  4.08   1.935  18.90   1   1     4     1
30.4    8  170.8  165  8.70   3.128  35.42   2   2     9     4
32.4    4   78.7   66  4.08   2.200  19.47   1   1     4     1
33.9    4   71.1   65  4.22   1.835  19.90   1   1     4     1

# 13. Pivot_Table()

In [92]:
df.pivot_table(values="mpg",index="am",aggfunc="sum")

      mpg
am
0   325.8
1   317.1

In [93]:
df.pivot_table(values="mpg",index="am",aggfunc="min")

     mpg
am
0   10.4
1   15.0

# 14. Merge()

In [94]:
cars = pd.DataFrame({"CarID": [1, 2, 3],
                     "Model": ["Mazda RX4", "Datsun 710", "Valiant"]})

price = pd.DataFrame({"CarID": [1, 2, 3],
                      "Price": [25000, 18000, 22000]})

merged = pd.merge(cars, price, on="CarID")

print(merged)

   CarID       Model  Price
0      1   Mazda RX4  25000
1      2  Datsun 710  18000
2      3     Valiant  22000

In [95]:
pd.merge(cars, price, on="CarID")

   CarID       Model  Price
0      1   Mazda RX4  25000
1      2  Datsun 710  18000
2      3     Valiant  22000

In [96]:
pd.merge(cars, price, on="CarID",how="right")

   CarID       Model  Price
0      1   Mazda RX4  25000
1      2  Datsun 710  18000
2      3     Valiant  22000

In [97]:
pd.merge(cars, price, on="CarID",how="left")

   CarID       Model  Price
0      1   Mazda RX4  25000
1      2  Datsun 710  18000
2      3     Valiant  22000

In [98]:
pd.merge(cars, price, on="CarID",how="inner")

   CarID       Model  Price
0      1   Mazda RX4  25000
1      2  Datsun 710  18000
2      3     Valiant  22000

In [99]:
pd.merge(cars, price, on="CarID",how="outer")

   CarID       Model  Price
0      1   Mazda RX4  25000
1      2  Datsun 710  18000
2      3     Valiant  22000

# 15. Concat()

In [100]:
pd.concat([cars,price]) # Combines Dataframes

   CarID       Model    Price
0      1   Mazda RX4      NaN
1      2  Datsun 710      NaN
2      3     Valiant      NaN
0      1         NaN  25000.0
1      2         NaN  18000.0
2      3         NaN  22000.0

In [101]:
pd.concat([cars,price], axis=1)

   CarID       Model  CarID  Price
0      1   Mazda RX4      1  25000
1      2  Datsun 710      2  18000
2      3     Valiant      3  22000

In [102]:
pd.concat([cars,price], axis=0)

   CarID       Model    Price
0      1   Mazda RX4      NaN
1      2  Datsun 710      NaN
2      3     Valiant      NaN
0      1         NaN  25000.0
1      2         NaN  18000.0
2      3         NaN  22000.0

# 16. Apply()

In [103]:
df["Efficiency"] = df["mpg"].apply(lambda x: "High" if x > 20 else "Low")
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Efficiency
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,High
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,High
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,High
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,High
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,Low

# 17. Map()

In [104]:
df["Transmission"]=df["am"].map({0:"automatic", # Values in a series
                                 1:"Manual"})
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Efficiency,Transmission
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,High,Manual
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,High,Manual
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,High,Manual
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,High,automatic
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,Low,automatic

# 18. Loc()

In [105]:
df.loc[:,["mpg","hp"]] # Specific Columns # Rows & Columns by label

                      mpg   hp
Mazda RX4            21.0  110
Mazda RX4 Wag        21.0  110
Datsun 710           22.8   93
Hornet 4 Drive       21.4  110
Hornet Sportabout    18.7  175
Valiant              18.1  105
Duster 360           14.3  245
Merc 240D            24.4   62
Merc 230             22.8   95
Merc 280             19.2  123
Merc 280C            17.8  123
Merc 450SE           16.4  180
Merc 450SL           17.3  180
Merc 450SLC          15.2  180
Cadillac Fleetwood   10.4  205
Lincoln Continental  10.4  215
Chrysler Imperial    14.7  230
Fiat 128             32.4   66
Honda Civic          30.4   52
Toyota Corolla       33.9   65
Toyota Corona        21.5   97
Dodge Challenger     15.5  150
AMC Javelin          15.2  150
Camaro Z28           13.3  245
Pontiac Firebird     19.2  175
Fiat X1-9            27.3   66
Porsche 914-2        26.0   91
Lotus Europa         30.4  113
Ford Pantera L       15.8  264
Ferrari Dino         19.7  175
Maserati Bora        15.0  335
Volvo 142E           21.4  109

In [106]:
df.loc[df["mpg"]>25] # Filter

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Efficiency,Transmission
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,High,Manual
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,High,Manual
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,High,Manual
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,High,Manual
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,High,Manual
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,High,Manual

# 19. Iloc()

In [107]:
df.iloc[0] # First rows

mpg               21.0
cyl                  6
disp             160.0
hp                 110
drat               3.9
wt                2.62
qsec             16.46
vs                   0
am                   1
gear                 4
carb                 4
Efficiency        High
Transmission    Manual
Name: Mazda RX4, dtype: object

In [108]:
df.iloc[:5] # First 5 Rows

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Efficiency,Transmission
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,High,Manual
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,High,Manual
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,High,Manual
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,High,automatic
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,Low,automatic

In [109]:
df.iloc[:5,[0,2,4]]

                    mpg   disp  drat
Mazda RX4          21.0  160.0  3.90
Mazda RX4 Wag      21.0  160.0  3.90
Datsun 710         22.8  108.0  3.85
Hornet 4 Drive     21.4  258.0  3.08
Hornet Sportabout  18.7  360.0  3.15

# 20. Query()

In [110]:
df.query("mpg > 25") # Car with mpg greater than 25

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Efficiency,Transmission
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,High,Manual
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,High,Manual
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,High,Manual
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,High,Manual
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,High,Manual
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,High,Manual

In [111]:
df.query("mpg > 20 and hp > 100") # Multiple conditions

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Efficiency,Transmission
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,High,Manual
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,High,Manual
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,High,automatic
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,High,Manual
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,High,Manual

# 21.Isin()

In [112]:
df[df["cyl"].isin([4,6])] # Find cars with 4 or 6 cylinders

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Efficiency,Transmission
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,High,Manual
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,High,Manual
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,High,Manual
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,High,automatic
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,Low,automatic
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,High,automatic
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,High,automatic
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,Low,automatic
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,Low,automatic
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,High,Manual
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,High,Manual
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,High,Manual
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,High,automatic
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,High,Manual
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,High,Manual
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,High,Manual
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,Low,Manual
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,High,Manual

# 22. Between()

In [113]:
df[df["mpg"].between(20,30)]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Efficiency,Transmission
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,High,Manual
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,High,Manual
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,High,Manual
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,High,automatic
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,High,automatic
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,High,automatic
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,High,automatic
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,High,Manual
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,High,Manual
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,High,Manual

# 23. Drop()

In [114]:
df.drop("gear", axis=1) # Remove a column

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,carb,Efficiency,Transmission
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,High,Manual
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,High,Manual
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,1,High,Manual
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,1,High,automatic
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,2,Low,automatic
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,1,Low,automatic
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,4,Low,automatic
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,2,High,automatic
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,2,High,automatic
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,Low,automatic
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,Low,automatic
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,Low,automatic
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,Low,automatic
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,Low,automatic
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,4,Low,automatic
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,4,Low,automatic
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,4,Low,automatic
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,1,High,Manual
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,2,High,Manual
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,1,High,Manual
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,1,High,automatic
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,2,Low,automatic
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,2,Low,automatic
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,4,Low,automatic
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,2,Low,automatic
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,1,High,Manual
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,2,High,Manual
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,2,High,Manual
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,4,Low,Manual
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,6,Low,Manual
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,8,Low,Manual
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,2,High,Manual

In [115]:
df.drop(["gear","carb"], axis=1) # Remove multiple columns

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,Efficiency,Transmission
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,High,Manual
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,High,Manual
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,High,Manual
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,High,automatic
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,Low,automatic
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,Low,automatic
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,Low,automatic
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,High,automatic
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,High,automatic
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,Low,automatic
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,Low,automatic
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,Low,automatic
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,Low,automatic
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,Low,automatic
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,Low,automatic
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,Low,automatic
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,Low,automatic
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,High,Manual
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,High,Manual
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,High,Manual
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,High,automatic
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,Low,automatic
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,Low,automatic
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,Low,automatic
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,Low,automatic
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,High,Manual
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,High,Manual
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,High,Manual
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,Low,Manual
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,Low,Manual
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,Low,Manual
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,High,Manual

# 24.Rename()

In [116]:
df.rename(columns={"mpg":"Mileage"})

,Mileage,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Efficiency,Transmission
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,High,Manual
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,High,Manual
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,High,Manual
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,High,automatic
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,Low,automatic
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,Low,automatic
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,Low,automatic
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,High,automatic
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,High,automatic
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,Low,automatic
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,Low,automatic
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,Low,automatic
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,Low,automatic
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,Low,automatic
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,Low,automatic
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,Low,automatic
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,Low,automatic
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,High,Manual
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,High,Manual
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,High,Manual
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,High,automatic
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,Low,automatic
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,Low,automatic
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,Low,automatic
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,Low,automatic
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,High,Manual
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,High,Manual
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,High,Manual
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,Low,Manual
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,Low,Manual
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,Low,Manual
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,High,Manual

# 25. Fillna()

In [117]:
df["mpg"] = df["mpg"].fillna(df["mpg"].mean())
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Efficiency,Transmission
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,High,Manual
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,High,Manual
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,High,Manual
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,High,automatic
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,Low,automatic

# 26. Dropna()

In [118]:
df.dropna() # Remove missing values

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Efficiency,Transmission
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,High,Manual
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,High,Manual
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,High,Manual
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,High,automatic
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,Low,automatic
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,Low,automatic
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,Low,automatic
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,High,automatic
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,High,automatic
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,Low,automatic
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,Low,automatic
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,Low,automatic
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,Low,automatic
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,Low,automatic
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,Low,automatic
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,Low,automatic
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,Low,automatic
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,High,Manual
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,High,Manual
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,High,Manual
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,High,automatic
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,Low,automatic
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,Low,automatic
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,Low,automatic
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,Low,automatic
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,High,Manual
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,High,Manual
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,High,Manual
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,Low,Manual
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,Low,Manual
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,Low,Manual
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,High,Manual

# 27. Replace()

In [122]:
df["am"]=df["am"].replace({0:"Automatic", 1:"Manual"})  #Replace values
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,Manual,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,Manual,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,Manual,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,Automatic,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,Automatic,3,2

# 28.Duplicate()

In [125]:
df.duplicate()

AttributeError: 'DataFrame' object has no attribute 'duplicate'

In [126]:
df.duplicate().sum()

AttributeError: 'DataFrame' object has no attribute 'duplicate'

# 29. Drop_Duplicate()

In [127]:
df.drop_duplicate()

AttributeError: 'DataFrame' object has no attribute 'drop_duplicate'

# 30.To_datetime()

In [137]:
df["purchase_date"]=["2024-01-01"]*len(df)
df["purchase_date"]=pd.to_datetime(df["purchase_date"])
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,purchase_date
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,Manual,4,4,2024-01-01
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,Manual,4,4,2024-01-01
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,Manual,4,1,2024-01-01
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,Automatic,3,1,2024-01-01
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,Automatic,3,2,2024-01-01

# 31. Astype()

In [141]:
df["gear"] = df["gear"].astype("category")
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, Mazda RX4 to Volvo 142E
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   mpg            32 non-null     float64
 1   cyl            32 non-null     int64
 2   disp           32 non-null     float64
 3   hp             32 non-null     int64
 4   drat           32 non-null     float64
 5   wt             32 non-null     float64
 6   qsec           32 non-null     float64
 7   vs             32 non-null     int64
 8   am             32 non-null     object
 9   gear           32 non-null     category
 10  carb           32 non-null     int64
 11  purchase_date  32 non-null     datetime64[ns]
dtypes: category(1), datetime64[ns](1), float64(5), int64(4), object(1)
memory usage: 3.2+ KB

In [144]:
df["gear"] = df["gear"].astype("object")
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, Mazda RX4 to Volvo 142E
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   mpg            32 non-null     float64
 1   cyl            32 non-null     int64
 2   disp           32 non-null     float64
 3   hp             32 non-null     int64
 4   drat           32 non-null     float64
 5   wt             32 non-null     float64
 6   qsec           32 non-null     float64
 7   vs             32 non-null     int64
 8   am             32 non-null     object
 9   gear           32 non-null     object
 10  carb           32 non-null     int64
 11  purchase_date  32 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(5), int64(4), object(2)
memory usage: 3.2+ KB