In [2]:
import pandas as pd
from pydataset import data
df = data("mtcars")
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [4]:
pd.pivot_table(df,values ="mpg",index="cyl") # Avg MPG by num of cyls

           mpg
cyl
4    26.663636
6    19.742857
8    15.100000

In [6]:
pd.pivot_table(df,values="hp",index="cyl",aggfunc="sum") # total hp by cyls

       hp
cyl
4     909
6     856
8    2929

In [7]:
pd.pivot_table(df,values="mpg",index="cyl",aggfunc="count") # Num of Cars in each Cyls group

     mpg
cyl
4     11
6      7
8     14

In [8]:
pd.pivot_table(df,values=["mpg","hp"],index="cyl") # Avg MPG & HP

             hp        mpg
cyl
4     82.636364  26.663636
6    122.285714  19.742857
8    209.214286  15.100000

In [9]:
pd.pivot_table(df,values="mpg",index="cyl",aggfunc=["mean","max","min"]) # Multiple Aggregations

          mean   max   min
           mpg   mpg   mpg
cyl
4    26.663636  33.9  21.4
6    19.742857  21.4  17.8
8    15.100000  19.2  10.4

In [12]:
pd.pivot_table(df,values="mpg",index="cyl",columns="am",aggfunc="mean") # Two Dimensional Pivot. Avg MPG by Cyl & Am

am        0          1
cyl
4    22.900  28.075000
6    19.125  20.566667
8    15.050  15.400000

In [13]:
pd.pivot_table(df,values="hp",index="gear",columns="am",aggfunc="mean") # Avg Hp

am             0        1
gear
3     176.133333      NaN
4     100.750000   83.875
5            NaN  195.600

In [14]:
pd.pivot_table(df,values="mpg",index=["cyl","gear"]) # Multiple Indexs

             mpg
cyl gear
4   3     21.500
    4     26.925
    5     28.200
6   3     19.750
    4     19.750
    5     19.700
8   3     15.050
    5     15.400

In [15]:
pd.pivot_table(df,values=["mpg","hp"],index=["cyl","gear"]) # Multiple Values & Multiple Indexs

                  hp     mpg
cyl gear
4   3      97.000000  21.500
    4      76.000000  26.925
    5     102.000000  28.200
6   3     107.500000  19.750
    4     116.500000  19.750
    5     175.000000  19.700
8   3     194.166667  15.050
    5     299.500000  15.400

In [18]:
pd.pivot_table(df,values="mpg",index="cyl")

           mpg
cyl
4    26.663636
6    19.742857
8    15.100000

In [17]:
pd.pivot_table(df,values="mpg",index="cyl",columns="gear")

gear      3       4     5
cyl
4     21.50  26.925  28.2
6     19.75  19.750  19.7
8     15.05     NaN  15.4

# Fill Missing Values

In [16]:
pd.pivot_table(df,values="mpg",index="cyl",columns="gear",fill_value=0) # Fill missing values

gear      3       4     5
cyl
4     21.50  26.925  28.2
6     19.75  19.750  19.7
8     15.05   0.000  15.4

In [22]:
pd.pivot_table(df,values="mpg",index="cyl",columns="gear",fill_value=555)

gear      3        4     5
cyl
4     21.50   26.925  28.2
6     19.75   19.750  19.7
8     15.05  555.000  15.4

# Grand Total(Margins)

In [24]:
pd.pivot_table(df,values="mpg",index="cyl",aggfunc="mean",margins=True) # All rows shows the overall Avg MPG

           mpg
cyl
4    26.663636
6    19.742857
8    15.100000
All  20.090625

In [25]:
pd.pivot_table(df,values="mpg",index="cyl",columns="am",margins=True) # Grand total with rows & columns

am           0          1        All
cyl
4    22.900000  28.075000  26.663636
6    19.125000  20.566667  19.742857
8    15.050000  15.400000  15.100000
All  17.147368  24.392308  20.090625

In [26]:
pd.pivot_table(df,values="wt",index="gear",aggfunc=["mean","sum","max","min"])

          mean     sum    max    min
            wt      wt     wt     wt
gear
3     3.892600  58.389  5.424  2.465
4     2.616667  31.400  3.440  1.615
5     2.632600  13.163  3.570  1.513

In [28]:
pd.pivot_table(df,values=["mpg","hp","wt"],index="cyl",columns="am",aggfunc="mean")

             hp                 mpg                   wt
am            0           1       0          1         0        1
cyl
4     84.666667   81.875000  22.900  28.075000  2.935000  2.04225
6    115.250000  131.666667  19.125  20.566667  3.388750  2.75500
8    194.166667  299.500000  15.050  15.400000  4.104083  3.37000

In [29]:
pd.pivot_table(df,values=["mpg","hp","wt"],index="cyl",columns="am",aggfunc="mean",fill_value=0)

             hp                 mpg                   wt
am            0           1       0          1         0        1
cyl
4     84.666667   81.875000  22.900  28.075000  2.935000  2.04225
6    115.250000  131.666667  19.125  20.566667  3.388750  2.75500
8    194.166667  299.500000  15.050  15.400000  4.104083  3.37000

# Interview Questions

# 1. Average MPG by Cylinders

In [30]:
pd.pivot_table(df,values="mpg",index="cyl",aggfunc="mean")

           mpg
cyl
4    26.663636
6    19.742857
8    15.100000

# 2. Average MPG by Cylinders & Transmission

In [34]:
pd.pivot_table(df,values="mpg",index="cyl",columns="am",aggfunc="mean")

am        0          1
cyl
4    22.900  28.075000
6    19.125  20.566667
8    15.050  15.400000

# 3. Total Horsepower by Gear

In [35]:
pd.pivot_table(df,values="hp",index="gear",aggfunc="sum")

        hp
gear
3     2642
4     1074
5      978

# 4. Count Cars By Transmissions

In [36]:
pd.pivot_table(df,values="mpg",index="am",aggfunc="count")

    mpg
am
0    19
1    13

# 5. Average Weight By Gear

In [37]:
pd.pivot_table(df,values="wt",index="gear",aggfunc="mean")

            wt
gear
3     3.892600
4     2.616667
5     2.632600

# 6. Compare Manual Vs Automatic Cars

In [38]:
pd.pivot_table(df,values=["mpg","hp","wt"],index="am",aggfunc="mean")

            hp        mpg        wt
am
0   160.263158  17.147368  3.768895
1   126.846154  24.392308  2.411000

# 7. Multiple Aggregations(Mean,Max,Min)

In [39]:
pd.pivot_table(df,values="mpg",index="cyl",aggfunc=["mean","max","min"])

          mean   max   min
           mpg   mpg   mpg
cyl
4    26.663636  33.9  21.4
6    19.742857  21.4  17.8
8    15.100000  19.2  10.4

# 8. Add Grand Totals Using Margins=True

In [40]:
pd.pivot_table(df,values="mpg",index="cyl",aggfunc="mean",margins=True)

           mpg
cyl
4    26.663636
6    19.742857
8    15.100000
All  20.090625

# 9. Replace Missing Values Using Fill_Value

In [41]:
pd.pivot_table(df,values="mpg",index="cyl",columns="gear",fill_value=0)

gear      3       4     5
cyl
4     21.50  26.925  28.2
6     19.75  19.750  19.7
8     15.05   0.000  15.4

# 10. Multiple Rows & Columns Groupings

In [42]:
pd.pivot_table(df,values=["mpg","hp"],index=["cyl","gear"],columns="am",aggfunc="mean",fill_value=0,margins=True)

                  hp                                mpg
am                 0           1         All          0          1        All
cyl gear
4   3      97.000000    0.000000   97.000000  21.500000   0.000000  21.500000
    4      78.500000   75.166667   76.000000  23.600000  28.033333  26.925000
    5       0.000000  102.000000  102.000000   0.000000  28.200000  28.200000
6   3     107.500000    0.000000  107.500000  19.750000   0.000000  19.750000
    4     123.000000  110.000000  116.500000  18.500000  21.000000  19.750000
    5       0.000000  175.000000  175.000000   0.000000  19.700000  19.700000
8   3     194.166667    0.000000  194.166667  15.050000   0.000000  15.050000
    5       0.000000  299.500000  299.500000   0.000000  15.400000  15.400000
All       160.263158  126.846154  146.687500  17.147368  24.392308  20.090625